/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tms.util.dataEntity;

import com.tms.model.entity.Country;
import java.util.LinkedList;
import java.util.List;

/**
 *
 * @author sdrahnea
 */
public class CountryDataEntity {

    public static List<Country> getCountryData() {
        List<Country> countries = new LinkedList<>();

        Integer index = 0;

        countries.add(new Country(index++, "Afghanistan"));
        countries.add(new Country(index++, "Aland Islands"));
        countries.add(new Country(index++, "Albania"));
        countries.add(new Country(index++, "Algeria"));
        countries.add(new Country(index++, "American Samoa"));
        countries.add(new Country(index++, "Andorra"));
        countries.add(new Country(index++, "Angola"));
        countries.add(new Country(index++, "Anguilla"));
        countries.add(new Country(index++, "Antarctica"));
        countries.add(new Country(index++, "Antigua and Barbuda"));
        countries.add(new Country(index++, "Argentina"));
        countries.add(new Country(index++, "Armenia"));
        countries.add(new Country(index++, "Aruba"));
        countries.add(new Country(index++, "Ascension Island"));
        countries.add(new Country(index++, "Australia"));
        countries.add(new Country(index++, "Austria"));
        countries.add(new Country(index++, "Azerbaijan"));
        countries.add(new Country(index++, "Bahamas"));
        countries.add(new Country(index++, "Bahrain"));
        countries.add(new Country(index++, "Bangladesh"));
        countries.add(new Country(index++, "Barbados"));
        countries.add(new Country(index++, "Belarus"));
        countries.add(new Country(index++, "Belgium"));
        countries.add(new Country(index++, "Belize"));
        countries.add(new Country(index++, "Benin"));
        countries.add(new Country(index++, "Bermuda"));
        countries.add(new Country(index++, "Bhutan"));
        countries.add(new Country(index++, "Bolivia"));
        countries.add(new Country(index++, "Bosnia and Herzegovina"));
        countries.add(new Country(index++, "Botswana"));
        countries.add(new Country(index++, "Bouvet Island"));
        countries.add(new Country(index++, "Brazil"));
        countries.add(new Country(index++, "British Antarctic Territory"));
        countries.add(new Country(index++, "British Indian Ocean Territory"));
        countries.add(new Country(index++, "British Virgin Islands"));
        countries.add(new Country(index++, "Brunei"));
        countries.add(new Country(index++, "Bulgaria"));
        countries.add(new Country(index++, "Burkina Faso"));
        countries.add(new Country(index++, "Burma"));
        countries.add(new Country(index++, "Burundi"));
        countries.add(new Country(index++, "Cambodia"));
        countries.add(new Country(index++, "Cameroon"));
        countries.add(new Country(index++, "Canada"));
        countries.add(new Country(index++, "Canary Islands"));
        countries.add(new Country(index++, "Canton and Enderbury Islands"));
        countries.add(new Country(index++, "Cape Verde"));
        countries.add(new Country(index++, "Cayman Islands"));
        countries.add(new Country(index++, "Central African Republic"));
        countries.add(new Country(index++, "Ceuta and Melilla"));
        countries.add(new Country(index++, "Chad"));
        countries.add(new Country(index++, "Chile"));
        countries.add(new Country(index++, "China"));
        countries.add(new Country(index++, "Christmas Island"));
        countries.add(new Country(index++, "Clipperton Island"));
        countries.add(new Country(index++, "Cocos [Keeling] Islands"));
        countries.add(new Country(index++, "Colombia"));
        countries.add(new Country(index++, "Comoros"));
        countries.add(new Country(index++, "Congo - Brazzaville"));
        countries.add(new Country(index++, "Congo - Kinshasa"));
        countries.add(new Country(index++, "Cook Islands"));
        countries.add(new Country(index++, "Costa Rica"));
        countries.add(new Country(index++, "Cote d'Ivoire"));
        countries.add(new Country(index++, "Croatia"));
        countries.add(new Country(index++, "Cuba"));
        countries.add(new Country(index++, "Cyprus"));
        countries.add(new Country(index++, "Czech Republic"));
        countries.add(new Country(index++, "Denmark"));
        countries.add(new Country(index++, "Diego Garcia"));
        countries.add(new Country(index++, "Djibouti"));
        countries.add(new Country(index++, "Dominica"));
        countries.add(new Country(index++, "Dominican Republic"));
        countries.add(new Country(index++, "Dronning Maud Land"));
        countries.add(new Country(index++, "East Germany"));
        countries.add(new Country(index++, "Ecuador"));
        countries.add(new Country(index++, "Egypt"));
        countries.add(new Country(index++, "El Salvador"));
        countries.add(new Country(index++, "Equatorial Guinea"));
        countries.add(new Country(index++, "Eritrea"));
        countries.add(new Country(index++, "Estonia"));
        countries.add(new Country(index++, "Ethiopia"));
        countries.add(new Country(index++, "European Union"));
        countries.add(new Country(index++, "Falkland Islands"));
        countries.add(new Country(index++, "Faroe Islands"));
        countries.add(new Country(index++, "Fiji"));
        countries.add(new Country(index++, "Finland"));
        countries.add(new Country(index++, "France"));
        countries.add(new Country(index++, "French Guiana"));
        countries.add(new Country(index++, "French Polynesia"));
        countries.add(new Country(index++, "French Southern and Antarctic Territories"));
        countries.add(new Country(index++, "French Southern Territories"));
        countries.add(new Country(index++, "Gabon"));
        countries.add(new Country(index++, "Gambia"));
        countries.add(new Country(index++, "Georgia"));
        countries.add(new Country(index++, "Germany"));
        countries.add(new Country(index++, "Ghana"));
        countries.add(new Country(index++, "Gibraltar"));
        countries.add(new Country(index++, "Greece"));
        countries.add(new Country(index++, "Greenland"));
        countries.add(new Country(index++, "Grenada"));
        countries.add(new Country(index++, "Guadeloupe"));
        countries.add(new Country(index++, "Guam"));
        countries.add(new Country(index++, "Guatemala"));
        countries.add(new Country(index++, "Guernsey"));
        countries.add(new Country(index++, "Guinea"));
        countries.add(new Country(index++, "Guinea-Bissau"));
        countries.add(new Country(index++, "Guyana"));
        countries.add(new Country(index++, "Haiti"));
        countries.add(new Country(index++, "Heard Island and McDonald Islands"));
        countries.add(new Country(index++, "Honduras"));
        countries.add(new Country(index++, "Hong Kong"));
        countries.add(new Country(index++, "Hungary"));
        countries.add(new Country(index++, "Iceland"));
        countries.add(new Country(index++, "India"));
        countries.add(new Country(index++, "Indonesia"));
        countries.add(new Country(index++, "Iran"));
        countries.add(new Country(index++, "Iraq"));
        countries.add(new Country(index++, "Ireland"));
        countries.add(new Country(index++, "Isle of Man"));
        countries.add(new Country(index++, "Israel"));
        countries.add(new Country(index++, "Italy"));
        countries.add(new Country(index++, "Jamaica"));
        countries.add(new Country(index++, "Japan"));
        countries.add(new Country(index++, "Jersey"));
        countries.add(new Country(index++, "Johnston Island"));
        countries.add(new Country(index++, "Jordan"));
        countries.add(new Country(index++, "Kazakhstan"));
        countries.add(new Country(index++, "Kenya"));
        countries.add(new Country(index++, "Kiribati"));
        countries.add(new Country(index++, "Korea, South"));
        countries.add(new Country(index++, "Kuwait"));
        countries.add(new Country(index++, "Kyrgyzstan"));
        countries.add(new Country(index++, "Laos"));
        countries.add(new Country(index++, "Latvia"));
        countries.add(new Country(index++, "Lebanon"));
        countries.add(new Country(index++, "Lesotho"));
        countries.add(new Country(index++, "Liberia"));
        countries.add(new Country(index++, "Libya"));
        countries.add(new Country(index++, "Liechtenstein"));
        countries.add(new Country(index++, "Lithuania"));
        countries.add(new Country(index++, "Luxembourg"));
        countries.add(new Country(index++, "Macau"));
        countries.add(new Country(index++, "Macedonia"));
        countries.add(new Country(index++, "Madagascar"));
        countries.add(new Country(index++, "Malawi"));
        countries.add(new Country(index++, "Malaysia"));
        countries.add(new Country(index++, "Maldives"));
        countries.add(new Country(index++, "Mali"));
        countries.add(new Country(index++, "Malta"));
        countries.add(new Country(index++, "Marshall Islands"));
        countries.add(new Country(index++, "Martinique"));
        countries.add(new Country(index++, "Mauritania"));
        countries.add(new Country(index++, "Mauritius"));
        countries.add(new Country(index++, "Mayotte"));
        countries.add(new Country(index++, "Metropolitan France"));
        countries.add(new Country(index++, "Mexico"));
        countries.add(new Country(index++, "Micronesia"));
        countries.add(new Country(index++, "Midway Islands"));
        countries.add(new Country(index++, "Moldova"));
        countries.add(new Country(index++, "Monaco"));
        countries.add(new Country(index++, "Mongolia"));
        countries.add(new Country(index++, "Montenegro"));
        countries.add(new Country(index++, "Montserrat"));
        countries.add(new Country(index++, "Morocco"));
        countries.add(new Country(index++, "Mozambique"));
        countries.add(new Country(index++, "Myanmar [Burma]"));
        countries.add(new Country(index++, "Namibia"));
        countries.add(new Country(index++, "Nauru"));
        countries.add(new Country(index++, "Nepal"));
        countries.add(new Country(index++, "Netherlands"));
        countries.add(new Country(index++, "Netherlands Antilles"));
        countries.add(new Country(index++, "Neutral Zone"));
        countries.add(new Country(index++, "New Caledonia"));
        countries.add(new Country(index++, "New Zealand"));
        countries.add(new Country(index++, "Nicaragua"));
        countries.add(new Country(index++, "Niger"));
        countries.add(new Country(index++, "Nigeria"));
        countries.add(new Country(index++, "Niue"));
        countries.add(new Country(index++, "Norfolk Island"));
        countries.add(new Country(index++, "North Korea"));
        countries.add(new Country(index++, "North Vietnam"));
        countries.add(new Country(index++, "Northern Mariana Islands"));
        countries.add(new Country(index++, "Norway"));
        countries.add(new Country(index++, "Oman"));
        countries.add(new Country(index++, "Outlying Oceania"));
        countries.add(new Country(index++, "Pacific Islands Trust Territory"));
        countries.add(new Country(index++, "Pakistan"));
        countries.add(new Country(index++, "Palau"));
        countries.add(new Country(index++, "Palestinian Territories"));
        countries.add(new Country(index++, "Panama"));
        countries.add(new Country(index++, "Panama Canal Zone"));
        countries.add(new Country(index++, "Papua New Guinea"));
        countries.add(new Country(index++, "Paraguay"));
        countries.add(new Country(index++, "People's Democratic Republic of Yemen"));
        countries.add(new Country(index++, "Peru"));
        countries.add(new Country(index++, "Philippines"));
        countries.add(new Country(index++, "Pitcairn Islands"));
        countries.add(new Country(index++, "Poland"));
        countries.add(new Country(index++, "Portugal"));
        countries.add(new Country(index++, "Puerto Rico"));
        countries.add(new Country(index++, "Qatar"));
        countries.add(new Country(index++, "Réunion"));
        countries.add(new Country(index++, "Romania"));
        countries.add(new Country(index++, "Russia"));
        countries.add(new Country(index++, "Rwanda"));
        countries.add(new Country(index++, "Saint Barthélemy"));
        countries.add(new Country(index++, "Saint Helena"));
        countries.add(new Country(index++, "Saint Kitts and Nevis"));
        countries.add(new Country(index++, "Saint Lucia"));
        countries.add(new Country(index++, "Saint Martin"));
        countries.add(new Country(index++, "Saint Pierre and Miquelon"));
        countries.add(new Country(index++, "Saint Vincent and the Grenadines"));
        countries.add(new Country(index++, "Samoa"));
        countries.add(new Country(index++, "San Marino"));
        countries.add(new Country(index++, "São Tomé and Príncipe"));
        countries.add(new Country(index++, "Saudi Arabia"));
        countries.add(new Country(index++, "Senegal"));
        countries.add(new Country(index++, "Serbia"));
        countries.add(new Country(index++, "Serbia and Montenegro"));
        countries.add(new Country(index++, "Seychelles"));
        countries.add(new Country(index++, "Sierra Leone"));
        countries.add(new Country(index++, "Singapore"));
        countries.add(new Country(index++, "Slovakia"));
        countries.add(new Country(index++, "Slovenia"));
        countries.add(new Country(index++, "Solomon Islands"));
        countries.add(new Country(index++, "Somalia"));
        countries.add(new Country(index++, "South Africa"));
        countries.add(new Country(index++, "South Georgia and the South Sandwich Islands"));
        countries.add(new Country(index++, "Spain"));
        countries.add(new Country(index++, "Sri Lanka"));
        countries.add(new Country(index++, "Sudan"));
        countries.add(new Country(index++, "Suriname"));
        countries.add(new Country(index++, "Svalbard and Jan Mayen"));
        countries.add(new Country(index++, "Swaziland"));
        countries.add(new Country(index++, "Sweden"));
        countries.add(new Country(index++, "Switzerland"));
        countries.add(new Country(index++, "Syria"));
        countries.add(new Country(index++, "Taiwan"));
        countries.add(new Country(index++, "Tajikistan"));
        countries.add(new Country(index++, "Tanzania"));
        countries.add(new Country(index++, "Thailand"));
        countries.add(new Country(index++, "Timor-Leste"));
        countries.add(new Country(index++, "Togo"));
        countries.add(new Country(index++, "Tokelau"));
        countries.add(new Country(index++, "Tonga"));
        countries.add(new Country(index++, "Trinidad and Tobago"));
        countries.add(new Country(index++, "Tristan da Cunha"));
        countries.add(new Country(index++, "Tunisia"));
        countries.add(new Country(index++, "Turkey"));
        countries.add(new Country(index++, "Turkmenistan"));
        countries.add(new Country(index++, "Turks and Caicos Islands"));
        countries.add(new Country(index++, "Tuvalu"));
        countries.add(new Country(index++, "U.S. Minor Outlying Islands"));
        countries.add(new Country(index++, "U.S. Miscellaneous Pacific Islands"));
        countries.add(new Country(index++, "U.S. Virgin Islands"));
        countries.add(new Country(index++, "Uganda"));
        countries.add(new Country(index++, "Ukraine"));
        countries.add(new Country(index++, "Union of Soviet Socialist Republics"));
        countries.add(new Country(index++, "United Arab Emirates"));
        countries.add(new Country(index++, "United Kingdom"));
        countries.add(new Country(index++, "United States"));
        countries.add(new Country(index++, "Unknown Region"));
        countries.add(new Country(index++, "Uruguay"));
        countries.add(new Country(index++, "Uzbekistan"));
        countries.add(new Country(index++, "Vanuatu"));
        countries.add(new Country(index++, "Vatican City"));
        countries.add(new Country(index++, "Venezuela"));
        countries.add(new Country(index++, "Vietnam"));
        countries.add(new Country(index++, "Wake Island"));
        countries.add(new Country(index++, "Wallis and Futuna"));
        countries.add(new Country(index++, "Western Sahara"));
        countries.add(new Country(index++, "Yemen"));
        countries.add(new Country(index++, "Zambia"));
        countries.add(new Country(index++, "Zimbabwe"));

        return countries;
    }

}
