/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tms.util.dataEntity;

import com.tms.model.entity.Country;
import java.util.LinkedList;
import java.util.List;

/**
 *
 * @author sdrahnea
 */
public class CountryDataEntity {

    public static List<Country> getCountryData() {
        List<Country> countries = new LinkedList<>();

        countries.add(new Country("Afghanistan"));
        countries.add(new Country("Aland Islands"));
        countries.add(new Country("Albania"));
        countries.add(new Country("Algeria"));
        countries.add(new Country("American Samoa"));
        countries.add(new Country("Andorra"));
        countries.add(new Country("Angola"));
        countries.add(new Country("Anguilla"));
        countries.add(new Country("Antarctica"));
        countries.add(new Country("Antigua and Barbuda"));
        countries.add(new Country("Argentina"));
        countries.add(new Country("Armenia"));
        countries.add(new Country("Aruba"));
        countries.add(new Country("Ascension Island"));
        countries.add(new Country("Australia"));
        countries.add(new Country("Austria"));
        countries.add(new Country("Azerbaijan"));
        countries.add(new Country("Bahamas"));
        countries.add(new Country("Bahrain"));
        countries.add(new Country("Bangladesh"));
        countries.add(new Country("Barbados"));
        countries.add(new Country("Belarus"));
        countries.add(new Country("Belgium"));
        countries.add(new Country("Belize"));
        countries.add(new Country("Benin"));
        countries.add(new Country("Bermuda"));
        countries.add(new Country("Bhutan"));
        countries.add(new Country("Bolivia"));
        countries.add(new Country("Bosnia and Herzegovina"));
        countries.add(new Country("Botswana"));
        countries.add(new Country("Bouvet Island"));
        countries.add(new Country("Brazil"));
        countries.add(new Country("British Antarctic Territory"));
        countries.add(new Country("British Indian Ocean Territory"));
        countries.add(new Country("British Virgin Islands"));
        countries.add(new Country("Brunei"));
        countries.add(new Country("Bulgaria"));
        countries.add(new Country("Burkina Faso"));
        countries.add(new Country("Burma"));
        countries.add(new Country("Burundi"));
        countries.add(new Country("Cambodia"));
        countries.add(new Country("Cameroon"));
        countries.add(new Country("Canada"));
        countries.add(new Country("Canary Islands"));
        countries.add(new Country("Canton and Enderbury Islands"));
        countries.add(new Country("Cape Verde"));
        countries.add(new Country("Cayman Islands"));
        countries.add(new Country("Central African Republic"));
        countries.add(new Country("Ceuta and Melilla"));
        countries.add(new Country("Chad"));
        countries.add(new Country("Chile"));
        countries.add(new Country("China"));
        countries.add(new Country("Christmas Island"));
        countries.add(new Country("Clipperton Island"));
        countries.add(new Country("Cocos [Keeling] Islands"));
        countries.add(new Country("Colombia"));
        countries.add(new Country("Comoros"));
        countries.add(new Country("Congo - Brazzaville"));
        countries.add(new Country("Congo - Kinshasa"));
        countries.add(new Country("Cook Islands"));
        countries.add(new Country("Costa Rica"));
        countries.add(new Country("Cote d'Ivoire"));
        countries.add(new Country("Croatia"));
        countries.add(new Country("Cuba"));
        countries.add(new Country("Cyprus"));
        countries.add(new Country("Czech Republic"));
        countries.add(new Country("Denmark"));
        countries.add(new Country("Diego Garcia"));
        countries.add(new Country("Djibouti"));
        countries.add(new Country("Dominica"));
        countries.add(new Country("Dominican Republic"));
        countries.add(new Country("Dronning Maud Land"));
        countries.add(new Country("East Germany"));
        countries.add(new Country("Ecuador"));
        countries.add(new Country("Egypt"));
        countries.add(new Country("El Salvador"));
        countries.add(new Country("Equatorial Guinea"));
        countries.add(new Country("Eritrea"));
        countries.add(new Country("Estonia"));
        countries.add(new Country("Ethiopia"));
        countries.add(new Country("European Union"));
        countries.add(new Country("Falkland Islands"));
        countries.add(new Country("Faroe Islands"));
        countries.add(new Country("Fiji"));
        countries.add(new Country("Finland"));
        countries.add(new Country("France"));
        countries.add(new Country("French Guiana"));
        countries.add(new Country("French Polynesia"));
        countries.add(new Country("French Southern and Antarctic Territories"));
        countries.add(new Country("French Southern Territories"));
        countries.add(new Country("Gabon"));
        countries.add(new Country("Gambia"));
        countries.add(new Country("Georgia"));
        countries.add(new Country("Germany"));
        countries.add(new Country("Ghana"));
        countries.add(new Country("Gibraltar"));
        countries.add(new Country("Greece"));
        countries.add(new Country("Greenland"));
        countries.add(new Country("Grenada"));
        countries.add(new Country("Guadeloupe"));
        countries.add(new Country("Guam"));
        countries.add(new Country("Guatemala"));
        countries.add(new Country("Guernsey"));
        countries.add(new Country("Guinea"));
        countries.add(new Country("Guinea-Bissau"));
        countries.add(new Country("Guyana"));
        countries.add(new Country("Haiti"));
        countries.add(new Country("Heard Island and McDonald Islands"));
        countries.add(new Country("Honduras"));
        countries.add(new Country("Hong Kong"));
        countries.add(new Country("Hungary"));
        countries.add(new Country("Iceland"));
        countries.add(new Country("India"));
        countries.add(new Country("Indonesia"));
        countries.add(new Country("Iran"));
        countries.add(new Country("Iraq"));
        countries.add(new Country("Ireland"));
        countries.add(new Country("Isle of Man"));
        countries.add(new Country("Israel"));
        countries.add(new Country("Italy"));
        countries.add(new Country("Jamaica"));
        countries.add(new Country("Japan"));
        countries.add(new Country("Jersey"));
        countries.add(new Country("Johnston Island"));
        countries.add(new Country("Jordan"));
        countries.add(new Country("Kazakhstan"));
        countries.add(new Country("Kenya"));
        countries.add(new Country("Kiribati"));
        countries.add(new Country("Korea, South"));
        countries.add(new Country("Kuwait"));
        countries.add(new Country("Kyrgyzstan"));
        countries.add(new Country("Laos"));
        countries.add(new Country("Latvia"));
        countries.add(new Country("Lebanon"));
        countries.add(new Country("Lesotho"));
        countries.add(new Country("Liberia"));
        countries.add(new Country("Libya"));
        countries.add(new Country("Liechtenstein"));
        countries.add(new Country("Lithuania"));
        countries.add(new Country("Luxembourg"));
        countries.add(new Country("Macau"));
        countries.add(new Country("Macedonia"));
        countries.add(new Country("Madagascar"));
        countries.add(new Country("Malawi"));
        countries.add(new Country("Malaysia"));
        countries.add(new Country("Maldives"));
        countries.add(new Country("Mali"));
        countries.add(new Country("Malta"));
        countries.add(new Country("Marshall Islands"));
        countries.add(new Country("Martinique"));
        countries.add(new Country("Mauritania"));
        countries.add(new Country("Mauritius"));
        countries.add(new Country("Mayotte"));
        countries.add(new Country("Metropolitan France"));
        countries.add(new Country("Mexico"));
        countries.add(new Country("Micronesia"));
        countries.add(new Country("Midway Islands"));
        countries.add(new Country("Moldova"));
        countries.add(new Country("Monaco"));
        countries.add(new Country("Mongolia"));
        countries.add(new Country("Montenegro"));
        countries.add(new Country("Montserrat"));
        countries.add(new Country("Morocco"));
        countries.add(new Country("Mozambique"));
        countries.add(new Country("Myanmar [Burma]"));
        countries.add(new Country("Namibia"));
        countries.add(new Country("Nauru"));
        countries.add(new Country("Nepal"));
        countries.add(new Country("Netherlands"));
        countries.add(new Country("Netherlands Antilles"));
        countries.add(new Country("Neutral Zone"));
        countries.add(new Country("New Caledonia"));
        countries.add(new Country("New Zealand"));
        countries.add(new Country("Nicaragua"));
        countries.add(new Country("Niger"));
        countries.add(new Country("Nigeria"));
        countries.add(new Country("Niue"));
        countries.add(new Country("Norfolk Island"));
        countries.add(new Country("North Korea"));
        countries.add(new Country("North Vietnam"));
        countries.add(new Country("Northern Mariana Islands"));
        countries.add(new Country("Norway"));
        countries.add(new Country("Oman"));
        countries.add(new Country("Outlying Oceania"));
        countries.add(new Country("Pacific Islands Trust Territory"));
        countries.add(new Country("Pakistan"));
        countries.add(new Country("Palau"));
        countries.add(new Country("Palestinian Territories"));
        countries.add(new Country("Panama"));
        countries.add(new Country("Panama Canal Zone"));
        countries.add(new Country("Papua New Guinea"));
        countries.add(new Country("Paraguay"));
        countries.add(new Country("People's Democratic Republic of Yemen"));
        countries.add(new Country("Peru"));
        countries.add(new Country("Philippines"));
        countries.add(new Country("Pitcairn Islands"));
        countries.add(new Country("Poland"));
        countries.add(new Country("Portugal"));
        countries.add(new Country("Puerto Rico"));
        countries.add(new Country("Qatar"));
        countries.add(new Country("Réunion"));
        countries.add(new Country("Romania"));
        countries.add(new Country("Russia"));
        countries.add(new Country("Rwanda"));
        countries.add(new Country("Saint Barthélemy"));
        countries.add(new Country("Saint Helena"));
        countries.add(new Country("Saint Kitts and Nevis"));
        countries.add(new Country("Saint Lucia"));
        countries.add(new Country("Saint Martin"));
        countries.add(new Country("Saint Pierre and Miquelon"));
        countries.add(new Country("Saint Vincent and the Grenadines"));
        countries.add(new Country("Samoa"));
        countries.add(new Country("San Marino"));
        countries.add(new Country("São Tomé and Príncipe"));
        countries.add(new Country("Saudi Arabia"));
        countries.add(new Country("Senegal"));
        countries.add(new Country("Serbia"));
        countries.add(new Country("Serbia and Montenegro"));
        countries.add(new Country("Seychelles"));
        countries.add(new Country("Sierra Leone"));
        countries.add(new Country("Singapore"));
        countries.add(new Country("Slovakia"));
        countries.add(new Country("Slovenia"));
        countries.add(new Country("Solomon Islands"));
        countries.add(new Country("Somalia"));
        countries.add(new Country("South Africa"));
        countries.add(new Country("South Georgia and the South Sandwich Islands"));
        countries.add(new Country("Spain"));
        countries.add(new Country("Sri Lanka"));
        countries.add(new Country("Sudan"));
        countries.add(new Country("Suriname"));
        countries.add(new Country("Svalbard and Jan Mayen"));
        countries.add(new Country("Swaziland"));
        countries.add(new Country("Sweden"));
        countries.add(new Country("Switzerland"));
        countries.add(new Country("Syria"));
        countries.add(new Country("Taiwan"));
        countries.add(new Country("Tajikistan"));
        countries.add(new Country("Tanzania"));
        countries.add(new Country("Thailand"));
        countries.add(new Country("Timor-Leste"));
        countries.add(new Country("Togo"));
        countries.add(new Country("Tokelau"));
        countries.add(new Country("Tonga"));
        countries.add(new Country("Trinidad and Tobago"));
        countries.add(new Country("Tristan da Cunha"));
        countries.add(new Country("Tunisia"));
        countries.add(new Country("Turkey"));
        countries.add(new Country("Turkmenistan"));
        countries.add(new Country("Turks and Caicos Islands"));
        countries.add(new Country("Tuvalu"));
        countries.add(new Country("U.S. Minor Outlying Islands"));
        countries.add(new Country("U.S. Miscellaneous Pacific Islands"));
        countries.add(new Country("U.S. Virgin Islands"));
        countries.add(new Country("Uganda"));
        countries.add(new Country("Ukraine"));
        countries.add(new Country("Union of Soviet Socialist Republics"));
        countries.add(new Country("United Arab Emirates"));
        countries.add(new Country("United Kingdom"));
        countries.add(new Country("United States"));
        countries.add(new Country("Unknown Region"));
        countries.add(new Country("Uruguay"));
        countries.add(new Country("Uzbekistan"));
        countries.add(new Country("Vanuatu"));
        countries.add(new Country("Vatican City"));
        countries.add(new Country("Venezuela"));
        countries.add(new Country("Vietnam"));
        countries.add(new Country("Wake Island"));
        countries.add(new Country("Wallis and Futuna"));
        countries.add(new Country("Western Sahara"));
        countries.add(new Country("Yemen"));
        countries.add(new Country("Zambia"));
        countries.add(new Country("Zimbabwe"));

        return countries;
    }

}
