/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tms.util.dataEntity;

import com.tms.model.entity.Language;
import java.util.LinkedList;
import java.util.List;

/**
 *
 * @author sdrahnea
 */
public class LanguageDataEntity {

    public static List<Language> list() {
        List<Language> result = new LinkedList<>();

        result.add(new Language("Abaza"));
        result.add(new Language("Abkhazian"));
        result.add(new Language("Achinese"));
        result.add(new Language("Acoli"));
        result.add(new Language("Adangme"));
        result.add(new Language("Adyghe"));
        result.add(new Language("Afar"));
        result.add(new Language("Afrihili"));
        result.add(new Language("Afrikaans"));
        result.add(new Language("Akan"));
        result.add(new Language("Akkadian"));
        result.add(new Language("Albanian"));
        result.add(new Language("Aleut"));
        result.add(new Language("Altaic"));
        result.add(new Language("American Sign Language"));
        result.add(new Language("Amharic"));
        result.add(new Language("Ancient Hebrew"));
        result.add(new Language("Arabic"));
        result.add(new Language("Aramaic"));
        result.add(new Language("Arapho"));
        result.add(new Language("Araucanian"));
        result.add(new Language("Arawak"));
        result.add(new Language("Armenian"));
        result.add(new Language("Assamese"));
        result.add(new Language("Asturian"));
        result.add(new Language("Austronesian"));
        result.add(new Language("Avaric"));
        result.add(new Language("Avestan"));
        result.add(new Language("Awadhi"));
        result.add(new Language("Aymara"));
        result.add(new Language("Azerbaijani"));
        result.add(new Language("Balinese"));
        result.add(new Language("Balochi"));
        result.add(new Language("Bambara"));
        result.add(new Language("Banda"));
        result.add(new Language("Bantu"));
        result.add(new Language("Basa"));
        result.add(new Language("Basque"));
        result.add(new Language("Batak"));
        result.add(new Language("Beja"));
        result.add(new Language("Belarusian"));
        result.add(new Language("Belorussian"));
        result.add(new Language("Bemba"));
        result.add(new Language("Bengali"));
        result.add(new Language("Berber"));
        result.add(new Language("Berber(Other)"));
        result.add(new Language("Bhili"));
        result.add(new Language("Bhojpuri"));
        result.add(new Language("Bhojpuri (& Tharu)"));
        result.add(new Language("Bihari"));
        result.add(new Language("Bini"));
        result.add(new Language("Bislama"));
        result.add(new Language("Bosnian"));
        result.add(new Language("Bosnian-Croatian-Serbian"));
        result.add(new Language("Brahui"));
        result.add(new Language("Braj"));
        result.add(new Language("Breton"));
        result.add(new Language("Buginese"));
        result.add(new Language("Bulgarian"));
        result.add(new Language("Bulgarian-Macedonian"));
        result.add(new Language("Buriat"));
        result.add(new Language("Burmese"));
        result.add(new Language("Caddo"));
        result.add(new Language("Cantonese"));
        result.add(new Language("Carib"));
        result.add(new Language("Catalan"));
        result.add(new Language("Caucasian"));
        result.add(new Language("Cebuano"));
        result.add(new Language("Cebuano (Bisayan)"));
        result.add(new Language("Chagatai"));
        result.add(new Language("Cham"));
        result.add(new Language("Chamorro"));
        result.add(new Language("Chechen"));
        result.add(new Language("Cherokee"));
        result.add(new Language("Chewa"));
        result.add(new Language("Cheyenne"));
        result.add(new Language("Chibcha"));
        result.add(new Language("Chin"));
        result.add(new Language("Chinese"));
        result.add(new Language("Chinese Cantonese"));
        result.add(new Language("Chinese Mandarin"));
        result.add(new Language("Chinookjargon"));
        result.add(new Language("Church Slavonic"));
        result.add(new Language("Church Slavonik"));
        result.add(new Language("Chuukese"));
        result.add(new Language("Chuvash"));
        result.add(new Language("Coctaw"));
        result.add(new Language("Cook Island Maori"));
        result.add(new Language("Coptic"));
        result.add(new Language("Cornish"));
        result.add(new Language("Corsican"));
        result.add(new Language("Cree"));
        result.add(new Language("Creek"));
        result.add(new Language("Creoles & Pidgins (French-based Other)"));
        result.add(new Language("Croatian"));
        result.add(new Language("Cushitic"));
        result.add(new Language("Czech"));
        result.add(new Language("Dakota"));
        result.add(new Language("Damara"));
        result.add(new Language("Danish"));
        result.add(new Language("Dari"));
        result.add(new Language("Dayak"));
        result.add(new Language("Delaware"));
        result.add(new Language("Dida"));
        result.add(new Language("Dinka"));
        result.add(new Language("Divehi"));
        result.add(new Language("Dogri"));
        result.add(new Language("Dravidian"));
        result.add(new Language("Duala"));
        result.add(new Language("Dutch"));
        result.add(new Language("Dyula"));
        result.add(new Language("Dzongkha"));
        result.add(new Language("Efik"));
        result.add(new Language("Egyptian(Ancient)"));
        result.add(new Language("Ekajuk"));
        result.add(new Language("Elamite"));
        result.add(new Language("English"));
        result.add(new Language("English CA"));
        result.add(new Language("English UK"));
        result.add(new Language("English US"));
        result.add(new Language("Erzya"));
        result.add(new Language("Eskimoto"));
        result.add(new Language("Esperanto"));
        result.add(new Language("Estonian"));
        result.add(new Language("Ewe"));
        result.add(new Language("Ewondo"));
        result.add(new Language("Fanagalo"));
        result.add(new Language("Fang"));
        result.add(new Language("Fanti"));
        result.add(new Language("Faroese"));
        result.add(new Language("Farsi (Persian)"));
        result.add(new Language("Fijian"));
        result.add(new Language("Filipino"));
        result.add(new Language("Finnish"));
        result.add(new Language("Finno-Ugrian"));
        result.add(new Language("Flemish"));
        result.add(new Language("Fon"));
        result.add(new Language("Formosan"));
        result.add(new Language("French"));
        result.add(new Language("French CA"));
        result.add(new Language("French Canadian"));
        result.add(new Language("French Switzerland"));
        result.add(new Language("Frisian"));
        result.add(new Language("Friulian"));
        result.add(new Language("Fula"));
        result.add(new Language("Fulani"));
        result.add(new Language("Ga"));
        result.add(new Language("Gaelic"));
        result.add(new Language("Galician"));
        result.add(new Language("Gan"));
        result.add(new Language("Ganda"));
        result.add(new Language("Gayo"));
        result.add(new Language("Geez"));
        result.add(new Language("Georgian"));
        result.add(new Language("German"));
        result.add(new Language("German Austria"));
        result.add(new Language("German Germany"));
        result.add(new Language("German Middle High (ca.1050-1500)"));
        result.add(new Language("German Old High (ca.750-1050"));
        result.add(new Language("Germanic(Other)"));
        result.add(new Language("Gikuyu"));
        result.add(new Language("Gilbertese"));
        result.add(new Language("Gondi"));
        result.add(new Language("Gothic"));
        result.add(new Language("Grebo"));
        result.add(new Language("Greek"));
        result.add(new Language("Greek (Ancient)"));
        result.add(new Language("Greenlandic"));
        result.add(new Language("Guarani"));
        result.add(new Language("Gujarati"));
        result.add(new Language("Haida"));
        result.add(new Language("Haitian"));
        result.add(new Language("Haitian Creole"));
        result.add(new Language("Hakka"));
        result.add(new Language("Hausa"));
        result.add(new Language("Hawaiian"));
        result.add(new Language("Hebrew"));
        result.add(new Language("Herero"));
        result.add(new Language("Hiligaynon"));
        result.add(new Language("Himachali"));
        result.add(new Language("Hindi"));
        result.add(new Language("Hindi-Urdu"));
        result.add(new Language("HiriMotu"));
        result.add(new Language("Hmong"));
        result.add(new Language("Hungarian"));
        result.add(new Language("Hupa"));
        result.add(new Language("I-kiribati"));
        result.add(new Language("Iban"));
        result.add(new Language("Ibo/Igbo"));
        result.add(new Language("Icelandic"));
        result.add(new Language("Igbo"));
        result.add(new Language("Ijo"));
        result.add(new Language("Ilocano"));
        result.add(new Language("Ilokano"));
        result.add(new Language("Iloko"));
        result.add(new Language("Indonesian"));
        result.add(new Language("Ingush"));
        result.add(new Language("Inuktitut"));
        result.add(new Language("Inupiak"));
        result.add(new Language("Iranian"));
        result.add(new Language("Irish"));
        result.add(new Language("Iroquoian"));
        result.add(new Language("Italian"));
        result.add(new Language("Jakartanese"));
        result.add(new Language("Japanese"));
        result.add(new Language("Javanese"));
        result.add(new Language("Judeo-Arabic"));
        result.add(new Language("Judeo-Persian"));
        result.add(new Language("Kabyle"));
        result.add(new Language("Kachin"));
        result.add(new Language("Kadazan"));
        result.add(new Language("Kalabari"));
        result.add(new Language("Kalmyk-Oirat"));
        result.add(new Language("Kamba"));
        result.add(new Language("Kannada"));
        result.add(new Language("Kannada (Kanarese)"));
        result.add(new Language("Kara-Kalpak"));
        result.add(new Language("Karen"));
        result.add(new Language("Kashmiri"));
        result.add(new Language("Kashubian"));
        result.add(new Language("Kawi"));
        result.add(new Language("Kayah"));
        result.add(new Language("Kazakh"));
        result.add(new Language("Kdazan"));
        result.add(new Language("Khasi"));
        result.add(new Language("Khmer"));
        result.add(new Language("Khmer (Cambodian)"));
        result.add(new Language("Khoisan"));
        result.add(new Language("Khotanese"));
        result.add(new Language("Kikuyu"));
        result.add(new Language("Kinyarwanda"));
        result.add(new Language("Kirghiz"));
        result.add(new Language("Kiribati"));
        result.add(new Language("Kirundi"));
        result.add(new Language("Klingon"));
        result.add(new Language("Komi"));
        result.add(new Language("Kongo"));
        result.add(new Language("Konkani"));
        result.add(new Language("Korean"));
        result.add(new Language("Kosovan"));
        result.add(new Language("Kosraean"));
        result.add(new Language("Kpelle"));
        result.add(new Language("Kru"));
        result.add(new Language("Kuanyama"));
        result.add(new Language("Kumyk"));
        result.add(new Language("Kurdish"));
        result.add(new Language("Kurmanji"));
        result.add(new Language("Kurukh"));
        result.add(new Language("Kusaie"));
        result.add(new Language("Kutenai"));
        result.add(new Language("Ladino"));
        result.add(new Language("Lahnda"));
        result.add(new Language("Lamba"));
        result.add(new Language("Lao"));
        result.add(new Language("Laotian"));
        result.add(new Language("Lao–Isan"));
        result.add(new Language("Latin"));
        result.add(new Language("Latvian"));
        result.add(new Language("Letzeburgesch"));
        result.add(new Language("Lezghian"));
        result.add(new Language("Lingala"));
        result.add(new Language("Lithuanian"));
        result.add(new Language("Loma"));
        result.add(new Language("Lombard"));
        result.add(new Language("Lozi"));
        result.add(new Language("Luba-Katanga"));
        result.add(new Language("Luiseno"));
        result.add(new Language("Lunda"));
        result.add(new Language("Luo (Kenya,Tanzania)"));
        result.add(new Language("Lushai"));
        result.add(new Language("Luxembourgeois"));
        result.add(new Language("Maay"));
        result.add(new Language("Maay Maay"));
        result.add(new Language("Macedonian"));
        result.add(new Language("Madurese"));
        result.add(new Language("Magahi"));
        result.add(new Language("Maithili"));
        result.add(new Language("Makasar"));
        result.add(new Language("Makuwa"));
        result.add(new Language("Malagasy"));
        result.add(new Language("Malay"));
        result.add(new Language("Malayalam"));
        result.add(new Language("Maltese"));
        result.add(new Language("Manado Malay"));
        result.add(new Language("Mandarin"));
        result.add(new Language("Mandingo"));
        result.add(new Language("Manipuri"));
        result.add(new Language("Manx"));
        result.add(new Language("Maori"));
        result.add(new Language("Marathi"));
        result.add(new Language("Mari"));
        result.add(new Language("Marshall"));
        result.add(new Language("Marwari"));
        result.add(new Language("Masai"));
        result.add(new Language("Mbundu"));
        result.add(new Language("Mende"));
        result.add(new Language("Meo"));
        result.add(new Language("Miao"));
        result.add(new Language("Micmac"));
        result.add(new Language("Min Bei"));
        result.add(new Language("Min Dong"));
        result.add(new Language("Minangkabau"));
        result.add(new Language("Mirpuri"));
        result.add(new Language("Moldavan"));
        result.add(new Language("Moldavian"));
        result.add(new Language("Mon-Khmer"));
        result.add(new Language("Mongo"));
        result.add(new Language("Mongolian"));
        result.add(new Language("Montenegrin"));
        result.add(new Language("Mordivian"));
        result.add(new Language("Mossi"));
        result.add(new Language("Mossi-Dagomba"));
        result.add(new Language("Muuong"));
        result.add(new Language("Nahuatl (Aztec)"));
        result.add(new Language("Nauru"));
        result.add(new Language("Navajo"));
        result.add(new Language("NdebeleNorth"));
        result.add(new Language("NdebeleSouth"));
        result.add(new Language("Ndongo"));
        result.add(new Language("Neapolitan"));
        result.add(new Language("Nepal"));
        result.add(new Language("Nepali"));
        result.add(new Language("Newari"));
        result.add(new Language("Niger-Kordofanian"));
        result.add(new Language("Nigerian"));
        result.add(new Language("Nilo-Saharan"));
        result.add(new Language("Niuean"));
        result.add(new Language("Norse"));
        result.add(new Language("Northern Berber"));
        result.add(new Language("Norwegian"));
        result.add(new Language("Norwegian(Bokmal)"));
        result.add(new Language("Nyamwezi"));
        result.add(new Language("Nyanja"));
        result.add(new Language("Nyankole"));
        result.add(new Language("Nyoro"));
        result.add(new Language("Nzima"));
        result.add(new Language("Ojibwe"));
        result.add(new Language("Oriya"));
        result.add(new Language("Oromo"));
        result.add(new Language("Osage"));
        result.add(new Language("Ossetic"));
        result.add(new Language("Ottoman"));
        result.add(new Language("Pahari"));
        result.add(new Language("Pahlavi"));
        result.add(new Language("Palauan"));
        result.add(new Language("Pali"));
        result.add(new Language("Pampangan"));
        result.add(new Language("Pangasinan"));
        result.add(new Language("Panjabi"));
        result.add(new Language("Papiamento"));
        result.add(new Language("Papuan-Australian"));
        result.add(new Language("Pashto"));
        result.add(new Language("Persian"));
        result.add(new Language("Persian (Farsi)"));
        result.add(new Language("Phoenician"));
        result.add(new Language("Pidgin English"));
        result.add(new Language("Pohnpeian"));
        result.add(new Language("Polish"));
        result.add(new Language("Portuguese"));
        result.add(new Language("Portuguese Brazilian"));
        result.add(new Language("Portuguese Creole"));
        result.add(new Language("Portuguese Portugal"));
        result.add(new Language("Prakritlanguages"));
        result.add(new Language("Punjabi"));
        result.add(new Language("Pushto"));
        result.add(new Language("Q'eqchi'/Kekchi"));
        result.add(new Language("Quechua"));
        result.add(new Language("Rajasthani"));
        result.add(new Language("Rangpuri"));
        result.add(new Language("Rarotongan"));
        result.add(new Language("Rhaeto-Rom (ROmansch)"));
        result.add(new Language("Romance(Other)"));
        result.add(new Language("Romanian"));
        result.add(new Language("Romany"));
        result.add(new Language("Rundi"));
        result.add(new Language("Russian"));
        result.add(new Language("Rwanda-Rundi"));
        result.add(new Language("Sadndawe"));
        result.add(new Language("Salishanlanguages"));
        result.add(new Language("SamaritanAramaic"));
        result.add(new Language("Samilanguages"));
        result.add(new Language("Samoan"));
        result.add(new Language("Sango"));
        result.add(new Language("Sanskrit"));
        result.add(new Language("Santali"));
        result.add(new Language("Sardinian"));
        result.add(new Language("Scots"));
        result.add(new Language("Selkup"));
        result.add(new Language("Semitic"));
        result.add(new Language("Serbian"));
        result.add(new Language("Serbo-Croat"));
        result.add(new Language("Serbo-Croatian"));
        result.add(new Language("Serer"));
        result.add(new Language("Sesotho (S. Sotho)"));
        result.add(new Language("Shan"));
        result.add(new Language("Shona"));
        result.add(new Language("Sicilian"));
        result.add(new Language("Sidamo"));
        result.add(new Language("Siksika"));
        result.add(new Language("Simplified Chinese"));
        result.add(new Language("Sindhi"));
        result.add(new Language("Sinhalese"));
        result.add(new Language("Sino-Tibetan"));
        result.add(new Language("Siouanlanguages"));
        result.add(new Language("Siswant"));
        result.add(new Language("SiSwati (Swazi)"));
        result.add(new Language("Slavic"));
        result.add(new Language("Slovak"));
        result.add(new Language("Slovenian"));
        result.add(new Language("Sogdian"));
        result.add(new Language("Somali"));
        result.add(new Language("Somba"));
        result.add(new Language("Songhai"));
        result.add(new Language("Sorani"));
        result.add(new Language("Sorbian"));
        result.add(new Language("Sotho-Tswana"));
        result.add(new Language("SouthAmericanIndian(Other)"));
        result.add(new Language("Southern Quechua"));
        result.add(new Language("Spanish"));
        result.add(new Language("Spanish European"));
        result.add(new Language("Spanish LA"));
        result.add(new Language("Sudanese Arabic"));
        result.add(new Language("Sukuma"));
        result.add(new Language("Sukuma–Nyamwezi"));
        result.add(new Language("Sundanese"));
        result.add(new Language("Susu"));
        result.add(new Language("Swahili"));
        result.add(new Language("Swedish"));
        result.add(new Language("Sylheti"));
        result.add(new Language("Sylhetti"));
        result.add(new Language("Syriac"));
        result.add(new Language("Tagalog"));
        result.add(new Language("Tahitian"));
        result.add(new Language("Taiwanese"));
        result.add(new Language("Tajik"));
        result.add(new Language("Tamang"));
        result.add(new Language("Tamashek"));
        result.add(new Language("Tamil"));
        result.add(new Language("Tamil India"));
        result.add(new Language("Tamil Sri Lanka"));
        result.add(new Language("Tatar"));
        result.add(new Language("Tatar-Bashkir"));
        result.add(new Language("Telugu"));
        result.add(new Language("Tetum"));
        result.add(new Language("Thai"));
        result.add(new Language("Tibetan"));
        result.add(new Language("Tigre"));
        result.add(new Language("Tigrinya"));
        result.add(new Language("Timne"));
        result.add(new Language("Tivi"));
        result.add(new Language("Tlingit"));
        result.add(new Language("Tok Pisin"));
        result.add(new Language("Tonga"));
        result.add(new Language("Traditional Chinese"));
        result.add(new Language("Truk"));
        result.add(new Language("Tshiluba"));
        result.add(new Language("Tsimshian"));
        result.add(new Language("Tsonga"));
        result.add(new Language("Tswana"));
        result.add(new Language("Tumbuka"));
        result.add(new Language("Turkish"));
        result.add(new Language("Turkmen"));
        result.add(new Language("Tuvaluan"));
        result.add(new Language("Tuvinian"));
        result.add(new Language("Twi"));
        result.add(new Language("Ugaritic"));
        result.add(new Language("Uighur"));
        result.add(new Language("Ukrainian"));
        result.add(new Language("Ulithian"));
        result.add(new Language("Umbundu"));
        result.add(new Language("Urdu"));
        result.add(new Language("Uyghur"));
        result.add(new Language("Uzbek"));
        result.add(new Language("Vai"));
        result.add(new Language("Valencia"));
        result.add(new Language("Venetian"));
        result.add(new Language("Vietnamese"));
        result.add(new Language("Visayan"));
        result.add(new Language("Volapük"));
        result.add(new Language("Votic"));
        result.add(new Language("Wakashanlanguages"));
        result.add(new Language("Walamo"));
        result.add(new Language("Waray"));
        result.add(new Language("Washo"));
        result.add(new Language("Welsh"));
        result.add(new Language("Woleaian"));
        result.add(new Language("Wolof"));
        result.add(new Language("Wu"));
        result.add(new Language("Xhosa"));
        result.add(new Language("Xiang"));
        result.add(new Language("Yakut"));
        result.add(new Language("Yao"));
        result.add(new Language("Yapese"));
        result.add(new Language("Yiddish"));
        result.add(new Language("Yoruba"));
        result.add(new Language("YZapotec"));
        result.add(new Language("Zenaga"));
        result.add(new Language("Zhuang"));
        result.add(new Language("Zhuang(Chuang)"));
        result.add(new Language("Zulu"));
        result.add(new Language("Zuni"));

        return result;
    }

}
